language: node_js
node_js: "stable"

addons:
  chrome: stable

notifications:
  email: false

before_install:
  - stty cols 80

script: "npm test"

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
